'use client';

import * as React from 'react';
import { Check, Download, FileJson, Upload } from 'lucide-react';
import {
  Alert,
  Badge,
  Button,
  Field,
  Textarea,
  describedBy,
  useToast,
} from '@/components/ui';
import { cn } from '@/lib/cn';
import type { BrandPack } from '@/lib/branding/pack';

/**
 * The white-label seam, made concrete.
 *
 * Everything a customer's visual identity consists of is one JSON object.
 * Download it, hand it to a designer, get it back, paste it in. Selling
 * the portal to the fifty-first college is that file plus a subdomain —
 * not a branch, not a stylesheet, not a component.
 *
 * Both directions go through the server so the file is canonical: the
 * download is what the validator produced, not what this form happened to
 * hold, and a pasted pack is checked by the same schema the registry loads
 * `brands/*.json` with. A pack that validates here boots.
 */

interface PackIssue {
  path: string;
  message: string;
}

interface PutResponse {
  ok?: boolean;
  pack?: BrandPack;
  report?: { passes: boolean; summary: string };
  error?: string;
  issues?: PackIssue[];
}

const FILE_NOTE = [
  'Generated by the branding studio.',
  '',
  'Only the seeds below are stored. The ten-stop ramps, hover states, tinted fills,',
  'dark mode and every text pairing are derived from them at render time — see',
  'src/lib/branding/tokens.ts. Drop this file in brands/, add one line to',
  'src/lib/branding/registry.ts, point a subdomain at it, and the portal is branded.',
  '',
  'Run `npm run brand:check` after changing a colour. Errors block publication;',
  'warnings do not.',
];

export function PackImportExport({
  /** The pack assembled from the current editor state. */
  pack,
  /** Filename stem and pack id — the tenant's subdomain. */
  packId,
  onLoad,
  className,
}: {
  pack: unknown | null;
  packId: string;
  /** Hands a validated pack back to the editor. */
  onLoad: (pack: BrandPack) => void;
  className?: string;
}) {
  const toast = useToast();

  const [pasted, setPasted] = React.useState('');
  const [checking, setChecking] = React.useState(false);
  const [exporting, setExporting] = React.useState(false);
  const [issues, setIssues] = React.useState<PackIssue[] | null>(null);
  const [parseError, setParseError] = React.useState<string | null>(null);
  const [candidate, setCandidate] = React.useState<BrandPack | null>(null);
  const [candidateNote, setCandidateNote] = React.useState<string | null>(null);

  const fileInput = React.useRef<HTMLInputElement>(null);

  async function validate(body: unknown): Promise<PutResponse & { status: number }> {
    const res = await fetch('/api/admin/branding', {
      method: 'PUT',
      headers: { 'content-type': 'application/json' },
      body: JSON.stringify(body),
    });
    const data = (await res.json()) as PutResponse;
    return { ...data, status: res.status };
  }

  async function handleExport() {
    if (!pack) return;
    setExporting(true);
    try {
      const result = await validate(pack);
      if (!result.pack) {
        setIssues(result.issues ?? null);
        toast.error(
          'That pack did not validate',
          result.error ?? 'The editor produced something the schema rejected.',
        );
        return;
      }

      download(`${packId}.json`, JSON.stringify({ $comment: FILE_NOTE, ...result.pack }, null, 2));
      toast.success(
        `Downloaded ${packId}.json`,
        result.report?.passes
          ? 'Validated against the same schema the registry loads packs with.'
          : 'Saved, but the contrast audit on this pack does not pass. Fix it before shipping.',
      );
      setIssues(null);
    } catch {
      toast.error('Could not reach the server', 'The pack was not downloaded. Try again.');
    } finally {
      setExporting(false);
    }
  }

  async function handleCheck() {
    setIssues(null);
    setParseError(null);
    setCandidate(null);
    setCandidateNote(null);

    let parsed: unknown;
    try {
      parsed = JSON.parse(pasted);
    } catch {
      setParseError('That is not valid JSON. Paste the whole file, braces included.');
      return;
    }

    setChecking(true);
    try {
      const result = await validate(stripNotes(parsed));
      if (!result.pack) {
        setIssues(result.issues ?? [{ path: '(root)', message: result.error ?? 'Rejected.' }]);
        return;
      }
      setCandidate(result.pack);
      setCandidateNote(result.report?.summary ?? null);
    } catch {
      setParseError('Could not reach the server. Nothing was changed.');
    } finally {
      setChecking(false);
    }
  }

  function handleFile(event: React.ChangeEvent<HTMLInputElement>) {
    const file = event.target.files?.[0];
    if (!file) return;
    file
      .text()
      .then((text) => {
        setPasted(text);
        setParseError(null);
        setIssues(null);
        setCandidate(null);
      })
      .catch(() => setParseError('That file could not be read.'));
    // Allow re-choosing the same file after an edit on disk.
    event.target.value = '';
  }

  return (
    <div className={cn('space-y-5', className)}>
      <p className="text-sm text-secondary">
        A customer&rsquo;s whole visual identity is this one file. Downloading it and dropping it in{' '}
        <code className="font-mono text-xs">brands/</code> is the entire onboarding path for a new
        college&rsquo;s look — there is deliberately no code to write, because the person doing it at
        11pm before a demo should not have to be able to write any.
      </p>

      {/* Export */}
      <section className="space-y-2">
        <h3 className="flex items-center gap-2 font-display text-md font-semibold">
          <Download className="size-4 text-muted" aria-hidden="true" />
          Export
        </h3>
        <p className="text-sm text-secondary">
          Writes <code className="font-mono text-xs">{packId}.json</code> exactly as the registry
          expects it, seeds only. It carries the settings this browser form cannot store — ink,
          marker, neutral chroma, the hero lines and the module switches.
        </p>
        <div className="flex flex-wrap items-center gap-2">
          <Button type="button" onClick={handleExport} loading={exporting} disabled={!pack}>
            <FileJson className="size-4" aria-hidden="true" />
            Download brand pack
          </Button>
          {!pack ? (
            <span className="text-xs text-danger-fg">
              Fix the invalid colour above before exporting.
            </span>
          ) : null}
        </div>
      </section>

      {/* Import */}
      <section className="space-y-3 border-t border-line pt-5">
        <h3 className="flex items-center gap-2 font-display text-md font-semibold">
          <Upload className="size-4 text-muted" aria-hidden="true" />
          Import
        </h3>

        <Field
          htmlFor="pack-paste"
          label="Paste a brand pack"
          hint="Checked against the same schema that loads brands/*.json at boot. Nothing is applied until you load it."
          error={parseError}
        >
          <Textarea
            id="pack-paste"
            value={pasted}
            onChange={(e) => setPasted(e.target.value)}
            rows={8}
            spellCheck={false}
            placeholder={'{\n  "id": "stmarys",\n  "color": { "primary": "#7B1E23" },\n  ...\n}'}
            className="font-mono text-xs"
            invalid={Boolean(parseError)}
            aria-describedby={describedBy('pack-paste', {
              hint: true,
              error: Boolean(parseError),
            })}
          />
        </Field>

        <div className="flex flex-wrap items-center gap-2">
          <Button type="button" variant="secondary" onClick={handleCheck} loading={checking} disabled={!pasted.trim()}>
            Check this pack
          </Button>

          <Button type="button" variant="ghost" onClick={() => fileInput.current?.click()}>
            Choose a .json file
          </Button>
          <input
            ref={fileInput}
            type="file"
            accept="application/json,.json"
            onChange={handleFile}
            className="sr-only"
            aria-label="Choose a brand pack file"
            tabIndex={-1}
          />
        </div>

        {issues?.length ? (
          <Alert tone="danger" title={`${issues.length} problem${issues.length === 1 ? '' : 's'} with that pack`}>
            <ul className="mt-1 space-y-1">
              {issues.map((issue, i) => (
                <li key={`${issue.path}-${i}`} className="flex flex-wrap gap-x-2">
                  <code className="font-mono text-xs font-semibold">{issue.path || '(root)'}</code>
                  <span>{issue.message}</span>
                </li>
              ))}
            </ul>
          </Alert>
        ) : null}

        {candidate ? (
          <Alert
            tone="success"
            title={`“${candidate.copy.portalName}” is a valid pack`}
            icon={<Check className="size-4" />}
          >
            <div className="mt-1 space-y-2">
              <p className="flex flex-wrap items-center gap-x-2 gap-y-1">
                <Badge tone="outline">{candidate.id}</Badge>
                <span>{candidate.copy.institutionName}</span>
              </p>
              {candidateNote ? <p>{candidateNote}</p> : null}
              <p>
                Loading it replaces every value in the editor. Nothing is published until you press
                Publish.
              </p>
              <Button
                type="button"
                size="sm"
                onClick={() => {
                  onLoad(candidate);
                  setCandidate(null);
                  setPasted('');
                  toast.success('Pack loaded into the editor', 'Review the preview, then publish.');
                }}
              >
                Load into the editor
              </Button>
            </div>
          </Alert>
        ) : null}
      </section>
    </div>
  );
}

/** JSON has no comments, so `$`-prefixed keys carry them. Drop them on the way in. */
function stripNotes(value: unknown): unknown {
  if (Array.isArray(value)) return value.map(stripNotes);
  if (value && typeof value === 'object') {
    const out: Record<string, unknown> = {};
    for (const [key, inner] of Object.entries(value as Record<string, unknown>)) {
      if (!key.startsWith('$')) out[key] = stripNotes(inner);
    }
    return out;
  }
  return value;
}

function download(filename: string, contents: string): void {
  const blob = new Blob([contents], { type: 'application/json' });
  const url = URL.createObjectURL(blob);
  const anchor = document.createElement('a');
  anchor.href = url;
  anchor.download = filename;
  document.body.appendChild(anchor);
  anchor.click();
  anchor.remove();
  URL.revokeObjectURL(url);
}
